<template>
	<Card>
		<template #content>
			<div v-if="aiConfig">
				<div class="mb-8">
					<label class="block text-sm mb-2" for="enabledInBots">{{ getText('AI model') }}</label>
					<div class="text-gray-500 text-xs mb-1">
						{{ getText('Ensure you have the model configured in the server, else the bot will not work.') }}
					</div>
					<Select
						required
						v-model="aiConfig.model"
						:filter="true"
						:options="models"
						option-label="name"
						option-value="id"
						:placeholder="getText('Select contexts')"
						:empty-filter-message="getText('No models found')"
						:maxSelectedLabels="3"
						class="w-full md:w-80"
					/>
				</div>

				<div v-if="isLocalAi">
					<div class="mb-8">
						<label class="block text-sm mb-2" for="enabledInBots">{{ getText('Temperature') }}</label>
						<div class="text-gray-500 text-xs mb-1">
							{{
								getText(
									'The temperature controls the randomness of the responses generated by the model. A low value will generate more predictable responses, while a high value will generate more creative responses.'
								)
							}}
						</div>
						<InputNumber
							:min="0"
							:max="100"
							:step="0.1"
							:show-buttons="true"
							placeholder="0.7"
							v-model="aiConfig.config.temperature"
							class="w-full md:w-80"
						/>
					</div>

					<div class="mb-8">
						<label class="block text-sm mb-2" for="enabledInBots">{{ getText('Top K') }}</label>
						<div class="text-gray-500 text-xs mb-1">
							{{
								getText(
									'Reduces the probability of generating nonsensical responses. A higher value (e.g. 100) will give more diverse responses, while a lower value (e.g. 10) will be more conservative.'
								)
							}}
						</div>
						<InputNumber
							:min="0"
							:max="100"
							:step="0.1"
							:show-buttons="true"
							placeholder="40"
							v-model="aiConfig.config.topK"
							class="w-full md:w-80"
						/>
					</div>

					<div class="mb-8">
						<label class="block text-sm mb-2" for="enabledInBots">{{ getText('Top P') }}</label>
						<div class="text-gray-500 text-xs mb-1">
							{{
								getText(
									'Works together with top-k. A higher value (e.g. 0.95) will generate more diverse text, while a lower value (e.g. 0.5) will generate more focused and conservative text.'
								)
							}}
						</div>
						<InputNumber
							:min="0.05"
							:max="1"
							:step="0.05"
							:show-buttons="true"
							placeholder="0.9"
							v-model="aiConfig.config.topP"
							class="w-full md:w-80"
						/>
					</div>
				</div>

				<div class="flex justify-end items-center">
					<Button @click="save" :label="getText('Save')" />
				</div>
			</div>
		</template>
	</Card>
</template>

<script setup lang="ts">
import { useAiConfig } from '@/components/aiConfig/useAiConfig'
import { getText } from '@/lang/getText'
import Card from 'primevue/card'
import Select from 'primevue/select'
import InputNumber from 'primevue/inputnumber'
import Button from 'primevue/button'
import { useToast } from 'primevue/usetoast'

const toast = useToast()
const { aiConfig, models, isLocalAi, getMine, saveConfig } = useAiConfig()

const save = async () => {
	if (!aiConfig.value) return

	try {
		await saveConfig(aiConfig.value)
		toast.add({
			severity: 'success',
			summary: getText('Saved'),
			detail: getText('Settings saved successfully'),
			life: 5000
		})
	} catch (error) {
		toast.add({
			severity: 'error',
			summary: getText('Error'),
			detail: getText('Error saving settings'),
			life: 5000
		})
	}
}

getMine()
</script>
